spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:7307/study?useSSL=false&serverTimezone=Asia/Seoul
    username: root
    password:
    maximumPoolSize: 5
    driver-class-name: com.mysql.cj.jdbc.Driver # MySQL 8.x 버전 이상을 사용할 경우

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update # 애플리케이션을 다시 시작할 때마다 테이블 스키마를 자동으로 업데이트하는 설정
    properties:
      hibernate:
        show_sql: true # Hibernate가 생성한 SQL 쿼리를 로그로 출력하도록 설정
        format_sql: true # 생성된 SQL 쿼리를 읽기 쉽게 포맷팅